name: Course Report

on:
  workflow_dispatch:
    inputs:
      courseCode:
        required: true
        type: string

      courseType:
        required: true
        type: string

      streamType:
        required: true
        type: string

      repo:
        required: true
        type: string

      branch:
        required: true
        type: string

jobs:

  debug:

    runs-on: ubuntu-latest

    steps:

      - name: Show Inputs
        run: |
          echo "Course Code: ${{ inputs.courseCode }}"
          echo "Course Type: ${{ inputs.courseType }}"
          echo "Stream Type: ${{ inputs.streamType }}"
          echo "Repo: ${{ inputs.repo }}"
          echo "Branch: ${{ inputs.branch }}"
          
      - name: Encode Repo
        run: |
          python3 -c "import urllib.parse print(urllib.parse.quote('${{ inputs.repo }}', safe=''))"

      - name: Download GitLab Repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          ENCODED_REPO=$(python3 -c "import urllib.parse print(urllib.parse.quote('${{ inputs.repo }}', safe=''))")

          echo "Encoded Repo:"
          echo $ENCODED_REPO

          curl \
            --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            -L \
            "https://gitlab.com/api/v4/projects/$ENCODED_REPO/repository/archive.zip?sha=${{ inputs.branch }}" \
            -o repo.zip

      - name: Verify Download
        run: |
          ls -lh
      - name: Download GitLab Repository
        run: | 
          echo "Downloading:"
          echo "${{ inputs.repo }}"
          echo "${{ inputs.branch }}"

      - name: Extract Repository
        run: |
          echo "Extracting Repo..."
          
      - name: Run Course Report
        run: |
          echo "Running Course Report..."

          jobs:


      - name: Show Inputs
        run: |
          echo "Course Code: ${{ inputs.courseCode }}"
          echo "Repo: ${{ inputs.repo }}"
          echo "Branch: ${{ inputs.branch }}"

