name: Workflow Dispatch Environment Input Example

on: 
    workflow_dispatch: 
        inputs: 
            environment: 
                description: "The environment to deploy to"
                required: true
                type: environment
            notify:
                    description: "Notify the team when deploying"
                    required: false
                    default: false
                    type: boolean

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "Deploying to ${{ github.event.inputs.environment }} environment"