name: Manual Trigger with Custom Input

on:
  workflow_dispatch:
    inputs:
      user_message:
        description: 'Custom message from Netlify UI'
        required: true
        default: 'Hello from the web UI'
        type: string

jobs:
    process-input:
        runs-on: ubuntu-latest
        steps:
            - run: echo "The user sent this message ${{ github.event.inputs.user_message }}"
